### ISSUE TITLE
False positives for requireSqlTemplateInQueryFunction

### ISSUE THREAD

**Issue by rplopes** [seegno/jscs-config-seegno#13]
This rule seems to suggest that for raw SQL queries, we should use the SQL template, like:

```
sequelize.query(sql`SELECT * FROM users`)
```

However, when we run jscs with `preset: seegno` without disabling this rule, we get errors like:

```
Use the `sql` tagged template literal for raw queries at X :
    32 |    let query = sql`UPDATE "Users" SET X`;
    33 |
    34 |    return sequelize.query(query)
-----------------------------------^
    35 |      .then(function(result) {
    36 |        done(null, result);
```

Based on my understanding of the rule, this looks like a false positive. Is my assumption correct, or am I misunderstanding something?

**Comment by ruiquelhas** [comment]
This is not exactly a false positive. The issue here is that the rule checks for whatever is provided as an argument to `sequelize.query()` and it's not possible to tie that value a variable, at least in the scope of the current rule.

An idea to make this work would be to discard this rule and create a new one called, for instance, `requireSqlTemplates` which would look for both variable declarations and `String` literals, check if they were `SQL` statements and ensure they were being wrapped using the proper template.

**Comment by rplopes** [comment]
I was starting to replace instances of:

```
let query = sql`QUERY`;
sequelize.query(query);
```

with:

```
sequelize.query(sql`QUERY`);
```

However, I've stumbled upon a new type of rule violation:

```
Use the `sql` tagged template literal for raw queries at X :
    29 |    let sequelize = migration.sequelize;
    30 |
    31 |    return sequelize.query(sql`UPDATE "Cards" SET X`, {
---------------------------------------------------------------------------------------------------^
    32 |        type: db.sequelize.QueryTypes.BULKUPDATE
    33 |      })
```

Here, the problem seems to be passing the hash `{ type: db.sequelize.QueryTypes.BULKUPDATE }` after the SQL template. Is this an issue with the rule, or something else that can be fixed in the code?

**Comment by ruiquelhas** [comment]
Same issue I described in my previous comment.

**Comment by scordeiro** [comment]
@ruiquelhas I found a case where exceptional `PostgreSQL` (non-SQL standard) queries for replication/backup purposes are false positives, specifically:

* *CREATE_REPLICATION_SLOT*
* *START_REPLICATION*
* *DROP_REPLICATION_SLOT*
* *IDENTIFY_SYSTEM*
* *TIMELINE_HISTORY*
* *BASE_BACKUP*

These commands are used when accessing PostgreSQL in replication mode.

More details here: http://www.postgresql.org/docs/current/static/protocol-replication.html
