### ISSUE TITLE
Installing should package

### ISSUE THREAD

**Issue by nunorafaelrocha** [seegno/jscs-config-seegno#22]
Since `should` package is registered as a `devDependency` and `peerDependency`, anyone that follows the instructions and isn't using `should` runs into an `UNMET PEER DEPENDENCY` warning followed by a `Cannot find module 'should'` error when running jscs.

The package is used in the `requireShouldAssertionExecution` rule, so I think we have two options: 

1. Move `should` from `devDependencies` to `dependencies`.
2. Add `should` to the [installation](https://github.com/seegno/jscs-config-seegno#installation) instructions on [README.md](https://github.com/seegno/jscs-config-seegno/blob/master/README.md).

**Comment by ruimarinho** [comment]
This is definitely a dependency, not a dev one. I probably think it'd be easier to simply list the methods where they are necessary.

**Comment by ruimarinho** [comment]
@ruiquelhas can you take of this? https://github.com/seegno/jscs-config-seegno/blame/master/src/rules/require-should-assertion-execution.js#L8 we can either cache this or mark this a dependency instead.

**Comment by ruimarinho** [comment]
I have a better solution for this I think - invoke the `require` call inside a try catch and only add this rule if the `should` package is installed. Since most dev envs will already have it, those who forget to install it or are simply not interested in loading it, will not suffer from it.

**Comment by fixe** [comment]
Not solved by #23. We still need to implement @ruimarinho suggestion.
