### ISSUE TITLE
Add `should.js` as a peer dependency

### ISSUE THREAD

**Issue by nunofgs** [seegno/jscs-config-seegno#27]
The `require-should-assertion-execution` rule requires should.js@8.x due to the assumptions it makes on the _Assertion_ prototype object.

Please consider adding `should.js` as a peer dependency for other dependees.

Note, here is the cryptic error you'll receive if you have should.js < 8.x:

```sh
$ jscs src/
expected undefined to be true
```

See https://github.com/seegno/sql-tag/pull/2 for more information.

**Comment by ruiquelhas** [comment]
We are dropping this preset.
